### ISSUE TITLE
As a thin plumber, I think some of the levels aren't as wide as they should be

### ISSUE THREAD

**Issue by MarioSMB** [z/xonotic-sxb.pk3dir#11]
Each of the levels (including their sub areas) should be a width of 5 blocks. Some aren't following this standard yet...  
5 blocks allows the main level geometry plus some back and front scene stuff (like bush), and provides some more 3 dimensional look to the levels.

**Comment by z** [comment]
- [x] 4-2
- [x] 5-1
- [x] 5-2
- [x] 5-3
- [x] 6-1
- [x] 6-2
- [x] 7-1
- [x] 7-2
- [x] 7-3
- [x] 8-1
- [x] 8-4
- [x] -1
- [x] -2
- [x] -3

**Comment by z** [comment]
^ meant #25 an #26
