### ISSUE TITLE
As a player, I want coinblock mechanics to work more like Mario

### ISSUE THREAD

**Issue by z** [z/xonotic-sxb.pk3dir#22]
Currently it spawns a coin above the brush and a player has to collect it.

In Super Mario Bros, the coinblock spawns an image of a coin, and the value is applied to Mario's coin count.

**Comment by MarioSMB** [comment]
This is actually technically feasible, by making the item spawn invisible at the player's location ($activator.origin), and show a coin model on top fade away. We'd just need to make sure the item fades away or is always taken, so as to avoid invisible junk left on the map.

For the coin model, it could actually be the block's breaking effect, and we have a hit block model inside the block.

**Comment by MarioSMB** [comment]
Silly me - just make it a target_items instead of spawning an actual item.
