### ISSUE TITLE
As a player, I want mapshots of all the maps

### ISSUE THREAD

**Issue by z** [z/xonotic-sxb.pk3dir#28]

**Comment by MarioSMB** [comment]
In the All-Stars version of SMB1, the intermission screen for the next level shows a picture with the vegetation style and enemies to be encountered, giving players a pretty good idea of what to expect.  
This could be a good style for the map screenshots...

**Comment by z** [comment]
v1 has all programmatically generated mapshots from the "raw" screenshots.

This is sem-automated, in that the screenshots are still manually taken.

Good for this release. We can revisit the more advanced mapshots we discussed for a future release.
